### ISSUE TITLE
PolicyConfigurationFactory.getPolicyConfigurationFactory() is not thread safe.

### ISSUE THREAD

**Issue by darranl** [eclipse-ee4j/authorization#48]
As this method is responsible for creating the singleton PolicyConfigurationFactory if it is called more than once concurrently multiple instances can be created.

**Comment by darranl** [comment]
Just created so I have an issue no but I will propose a PR.

**Comment by arjantijms** [comment]
Looks good at a glance, thanks Darran! I think we can merge this soon after Jakarta EE 8 is released.
