### ISSUE TITLE
Rename project to authorization

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/authorization#60]
The name of this GitHub project should be "authorization", i.e. https://github.com/eclipse-ee4j/jacc should become https://github.com/eclipse-ee4j/authorization

**Comment by arjantijms** [comment]
Related bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=559843

**Comment by keilw** [comment]
I saw the case for `jakarta.security.enterprise` in [Security API](https://github.com/eclipse-ee4j/security-api/tree/master/api) for the root package, to tell it apart from this, but the **GroupId** here sounds a little inconsistent. It matches the package for Jakarta Security but here it's just `jakarta.authorization`. 
Could we either have all of them with "jakarta.security" like the package or remove the "enterprise" from the groupId of Jakarta Security instead?

**Comment by arjantijms** [comment]
@keilw Can you open a new issue for your last comment? Since the project is now renamed here, I'll close this one ;)

**Comment by keilw** [comment]
Ok created #68
