### ISSUE TITLE
Do we need the parent?

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/authorization#78]
The Parent POM
```
 <groupId>org.eclipse.ee4j.jacc</groupId>
    <artifactId>jacc-parent</artifactId>
    <version>2.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
```
isn't used by either Spec or API, so is it of use anywhere?

**Comment by arjantijms** [comment]
Isn't it just used as an aggregator to build the api and spec projects?

**Comment by keilw** [comment]
If it's only used by Maven then it seems OK because there is no relation between this one and the Spec or API artifacts, but since they are independent I guess we could live with the "org.eclipse.ee4j.jacc" legacy name in this one?

**Comment by arjantijms** [comment]
I'm fine with renaming it as well.

p.s.

The efforts to rename all GitHub projects and CI jobs for all of the Jakarta specs etc still needs to be done as well. Authentication and Authorization are now pretty much the only ones for which this has been partially done.

**Comment by keilw** [comment]
I think it's not necessary, because the EJB Parent also has a groupId "org.eclipse.ee4j.ejb-api" while the API uses "jakarta.ejb", therefore it seems consistent.
