### ISSUE TITLE
Policy Context Handler property keys do not appear to have been Jakarta'ized in spec.

### ISSUE THREAD

**Issue by jvanhill** [eclipse-ee4j/authorization#80]
These are the few that I have seen, but there may be others:

- javax.security.auth.Subject.container 
  - Perhaps does not need to change since javax.security.auth.Subject is JavaSE class
  - See [4.6.1.1. Container Subject Policy Context Handler](https://jakarta.ee/specifications/authorization/2.0/authorization-spec-2.0-SNAPSHOT.html#a715)
- javax.ejb.EnterpriseBean
  - See [4.6.1.4. EnterpriseBean Policy Context Handler](https://jakarta.ee/specifications/authorization/2.0/authorization-spec-2.0-SNAPSHOT.html#a723)
- jakarta.ejb.arguments
  - Already changed
- javax.xml.soap.SOAPMessage
  - Removed from Java SE 11, assume new package will be jakarta.*
  - See [4.6.1.2. SOAPMessage Policy Context Handler](https://jakarta.ee/specifications/authorization/2.0/authorization-spec-2.0-SNAPSHOT.html#a719)
- javax.servlet.http.HttpServletRequest
  - See [4.6.1.3. HttpServletRequest Policy Context Handler](https://jakarta.ee/specifications/authorization/2.0/authorization-spec-2.0-SNAPSHOT.html#a721)

**Comment by arjantijms** [comment]
Great catch! The property keys are (unfortunately) not defined in the API, but in GlassFish 6.0 they are defined as follows:

```java
public static final String SUBJECT = "javax.security.auth.Subject.container";
public static final String ENTERPRISE_BEAN = "jakarta.ejb.EnterpriseBean";
public static final String EJB_ARGUMENTS = "jakarta.ejb.arguments";
public static final String SOAP_MESSAGE = "jakarta.xml.soap.SOAPMessage";
public static final String HTTP_SERVLET_REQUEST = "jakarta.servlet.http.HttpServletRequest";
```
