### ISSUE TITLE
Complete the Release of Authorization 2.0

### ISSUE THREAD

**Issue by Pandrex247** [eclipse-ee4j/authorization#95]
These are the remaining steps as per the spec-committee guide for the project team to complete to finalise the release of [Authorization 2.0](https://github.com/jakartaee/specifications/pull/241):

- [x] Promote api staging release (the specification api jars) to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
- [x] Go through the merged jakarta.ee specification website page to verify all the links are valid.
- [x] Approve the compatibility request.
- [x] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
- [x] Merge any final release branch as appropriate for the branch management for the project.

**Comment by arjantijms** [comment]
Spec jars now available in central: https://repo1.maven.org/maven2/jakarta/authorization/jakarta.authorization-api/2.0.0

**Comment by arjantijms** [comment]
@Pandrex247: spec website hasn't been merged yet it seems: https://jakarta.ee/specifications/authorization/2.0/

It contains the content of the previous (milestone) release.

**Comment by arjantijms** [comment]
@Pandrex247 It's now updated. I found one link that's broken, which is for the SHA of the TCK. I'll do a new PR for that. It should be:

https://download.eclipse.org/jakartaee/authorization/2.0/jakarta-authorization-tck-2.0.0.zip.sha256

**Comment by arjantijms** [comment]
PR: https://github.com/jakartaee/specifications/pull/266

**Comment by arjantijms** [comment]
Closing out as all items have been checked off.
